platform :ios, '9.0'

target 'IronMan' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for IronMan

  target 'IronManTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'IronManUITests' do
    inherit! :search_paths
    # Pods for testing
  end

  pod 'Masonry'
  pod 'MWPhotoBrowser'
  pod 'CTAssetsPickerController'
  pod'MBProgressHUD'
  pod 'AFNetworking'
  pod 'PureLayout'
 
end
